добавил инфраструктуру генерации доки по тест кейсам в виде ридми
Byndyusoft/byndyusoft-dotnet-test-infrastructure pull request #7
Opened 2023-08-10 11:44 UTC by KozhevnikovDmitry

старую тулу по генерации csv отчёта - удалил

2023-08-14 07:14 UTC, AntonyNET approved these changes

2023-08-14 07:14 UTC, AntonyNET commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +        public TemplateNode Root => Parent is null ? this : Parent.Root;
рекурсия, все правильно, ошибок нет

2023-08-14 07:14 UTC, AntonyNET commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCasesExtractor.cs
> +                                       .Where(methodInfo => methodInfo.GetParameters().Any() == false)
лучше собирать такие кейсы, по которым не смогли собрать данные и выводить в отчете, а не проглатывать их

2023-08-14 07:22 UTC, Alex-Grigorichev requested changes

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +        ///     Имя файла для генерации документа по умолчанию
Если это имя файла используется по умолчанию, значит можно передать другое имя?

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +        private DirectoryInfo? GetSolutionDirectory(DirectoryInfo? dir)
что такое dir?

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +            if (dir == null)
Раньше по коду были проверки (smth is null), а тут (dir == null), исправить

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +            if (dir.GetFiles().Any(f => string.Equals(f.Extension.TrimStart('.'), "sln", StringComparison.OrdinalIgnoreCase)))
sln вынести в константу?

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReportModelBuilder.cs
> +                                                       .Select(category => new ReadmeCategory
вынести создании ReadmeCategory в отдельный метод, сейчас тяжело читать

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReportModelBuilder.cs
> +                                                                                                           .Select(subCategory => new ReadmeSubCategory
вынести создании ReadmeSubCategory в отдельный метод, сейчас тяжело читать

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReportModelBuilder.cs
> +                int count = 0;
linesCount?

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/ITestCaseData.cs
> +        /// <returns></returns>
удалить пустой returns

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/ITestCaseData.cs
> +    /// <typeparam name="T"></typeparam>
удалить

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/TestCaseDataAttribute.cs
> +    ///     Предоставляет источник тестовых данных для Теории.
Что такое Теории? Имеется ввиду [Theory]?

2023-08-14 07:22 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/TestCaseDataAttribute.cs
> +        public override IEnumerable<object[]> GetData(MethodInfo testMethod) => Activator.CreateInstance(Class) is ITestCaseData<TestCaseItemBase> instance ? Enumerable.Empty<object[]>().Append(new o
отформатировать

2023-08-14 09:50 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +        public int TestCount => Categories.Sum(category => category.TestCount);
++

2023-08-14 09:52 UTC, Alex-Grigorichev requested changes

2023-08-14 09:52 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +            return _children.FirstOrDefault(t => name.EqualsTrimmedIgnoreCase(t.Name.Trim()));
так ли нужно тут вызывать .Trim(), разве он не вызывается внутри метода EqualsTrimmedIgnoreCase?

2023-08-14 09:52 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +        ///     Ошибки валидации шаблона
О шаблоне отчёта readme, поправил коммент
++

2023-08-15 02:58 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +        public string? TemplateValidationErrors { get; set; }
Закрыл доступ в отчёте
++

2023-08-15 02:59 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +    ///     Шаблона отчёта представляется как дерево нод
++

2023-08-15 03:02 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +        public static TemplateNode CreateRoot()
Оставил параметризованный CreateRoot
++

2023-08-15 03:19 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +        private int Rank { get; set; }
++

2023-08-15 03:19 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +        public TemplateNode Root => Parent is null ? this : Parent.Root;
ок

2023-08-15 03:19 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCasesExtractor.cs
> +                                       .Where(methodInfo => methodInfo.GetParameters().Any() == false)
сделал 
++

2023-08-15 03:21 UTC, KozhevnikovDmitry commented on Directory.Build.props
> +		<Version>1.3.0</Version>
1.2.0 уже есть: https://www.nuget.org/packages/Byndyusoft.DotNet.Testing.Infrastructure/1.2.0

2023-08-15 03:22 UTC, KozhevnikovDmitry commented on README.md
> +Проект содержит вспомогательные объекты для использования в автоматических тестах.
Пока записал в карточку в notion

2023-08-15 03:25 UTC, KozhevnikovDmitry commented on README.md
> +Для создания отчёта установите в проекте пакет `Sod.Tests.Shared.IntegrationTests`  и создайте модульный тест примерно следующего содержания:
Sod.Tests.Shared.IntegrationTests - название содовского пакета, на основе которого сделан этот. Поправил, спасибо.
++
Изначально в соде это была инфра для интеграционников. Сейчас такой привязки нет. Можно и юниты документировать.

2023-08-15 03:30 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeCategory.cs
> +{
++

2023-08-15 03:31 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +            // тест-кейсы
Комментарий поправил на более информативный.
Комментарии в методе оставлю.

2023-08-15 03:32 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReportModelBuilder.cs
> +                int count = 0;
++

2023-08-15 03:33 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/ITestCaseData.cs
> +        /// <returns></returns>
++

2023-08-15 03:33 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/ITestCaseData.cs
> +    /// <typeparam name="T"></typeparam>
Заполнил коммент
++

2023-08-15 03:33 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/TestCaseDataAttribute.cs
> +    ///     Предоставляет источник тестовых данных для Теории.
Поправил коммент
++

2023-08-15 03:37 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/TestBase/TestCaseDataAttribute.cs
> +        public override IEnumerable<object[]> GetData(MethodInfo testMethod) => Activator.CreateInstance(Class) is ITestCaseData<TestCaseItemBase> instance ? Enumerable.Empty<object[]>().Append(new o
++

2023-08-15 05:29 UTC, Alex-Grigorichev commented on .github/workflows/pushOrPullRequest.yml
> +      - name: install dotnet 3.1
зачем устанавливать dotnet 3.1?

2023-08-15 05:30 UTC, Alex-Grigorichev commented on .github/workflows/release.yml
> +      - name: install dotnet 3.1
зачем устанавливать dotnet 3.1?

2023-08-15 06:33 UTC, DenisBaturinByndyusoft approved these changes

2023-08-15 09:27 UTC, KozhevnikovDmitry commented on .github/workflows/pushOrPullRequest.yml
> +      - name: install dotnet 3.1
Удалил установку 3.1
++

2023-08-15 09:27 UTC, KozhevnikovDmitry commented on .github/workflows/release.yml
> +      - name: install dotnet 3.1
Удалил установку 3.1

2023-08-15 09:27 UTC, KozhevnikovDmitry commented on .github/workflows/release.yml
> +      - name: install dotnet 3.1
++

2023-08-15 09:40 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +    public class ReportErrors
++

2023-08-15 09:40 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeSubCategory.cs
> +        public int TestCount { get; set; }
++

2023-08-15 09:43 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeSubCategory.cs
> +        public TestCase[] TestCases { get; set; } = default!;
Не более чем удобная модель для последующего формирования отчёта. Удобнее смотреть на отчёт как на дерево категорий с тестами в листьях.

2023-08-15 09:44 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +
++

2023-08-15 09:45 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +        private int Rank { get; set; }
++

2023-08-15 09:46 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +            var testCases = Categories.SelectMany(c => c.SubCategories.SelectMany(s => s.TestCases))
++

2023-08-15 09:46 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeReport.cs
> +        /// <summary>
++

2023-08-15 09:48 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/ReadmeSubCategory.cs
> +        public int Order { get; set; }
Поправил коммент
++

2023-08-15 09:49 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +        ///     Для нод подкатегорий всегда пустой словарь
Поправил коммент
++

2023-08-15 09:50 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/ReadmeMarkupBuilder.cs
> +        ///     Ссылка на раздел с общим описание отчёта
++

2023-08-15 09:51 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/StringExtensions.cs
> +namespace Byndyusoft.DotNet.Testing.Infrastructure.ReadmeGeneration.Services
++

2023-08-15 09:55 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeReportBuilder.cs
> +            foreach (var category in readmeReport.Categories
Не уверен, что так стало лучше, но ок.
++

2023-08-15 09:55 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeReportBuilder.cs
> +                foreach (var subCategory in category.SubCategories
Не уверен, что так стало лучше, но ок.
++

2023-08-15 09:55 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +        ///     Имя файла для генерации документа по умолчанию
Можно будет, когда в следующей версии расширим настройки

2023-08-15 09:56 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +        private DirectoryInfo? GetSolutionDirectory(DirectoryInfo? dir)
Поправил именование переменной
++

2023-08-15 09:57 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +            if (dir == null)
++

2023-08-15 10:01 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +            if (dir.GetFiles().Any(f => string.Equals(f.Extension.TrimStart('.'), "sln", StringComparison.OrdinalIgnoreCase)))
++

2023-08-15 10:02 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeReportBuilder.cs
> +        /// <summary>
Чтобы не ходить за ней в интерфейс. Долгий спор. Я предпочитаю видеть все комментарии к коду, когда его читаю. Актуально, когда читаешь код не из IDE.

2023-08-15 10:10 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReportModelBuilder.cs
> +                                                                                                           .Select(subCategory => new ReadmeSubCategory
Не уверен, что стало лучше, но ок.
++

2023-08-15 10:11 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReportModelBuilder.cs
> +                                                       .Select(category => new ReadmeCategory
Не уверен, что стало лучше, но ок.
++

2023-08-15 10:15 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Interfaces/ITestCaseSolutionReporter.cs
> +        Task<bool> Generate(params Assembly[] assemblies);
Сгенерированный отчёт ложится на диск.
Возвращаемый флажок нужен для того, чтобы иметь возможность завалить тест, который и будет перегенеривать отчёт. В подвале отчёта будут перечислены ошибки.

2023-08-15 10:17 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Interfaces/ITestCaseSolutionReporter.cs
> +        Task<bool> Generate(params Assembly[] assemblies);
Поправил название метода и коммент, чтобы лучше соотвествовали происходящему
++

2023-08-15 11:41 UTC, Alex-Grigorichev commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Services/TestCaseReadmeSolutionReporter.cs
> +        ///     Имя файла для генерации документа по умолчанию
Давай пока удалим "по умолчанию"?

2023-08-15 12:00 UTC, Alex-Grigorichev approved these changes

2023-08-15 13:40 UTC, merged

2023-08-16 03:23 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +    public int GetSubCategoryOrder(string? categoryName, string? subCategoryName)
Действительно сложные правила сортировки. Переписал комментарии, чтобы было понятнее. MaxValue убрал, чтобы не смущало=)

2023-08-16 03:23 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Entities/TemplateNode.cs
> +    public int GetCategoryOrder(string? categoryName)
Действительно сложные правила сортировки. Переписал комментарии, чтобы было понятнее.

2023-08-16 03:54 UTC, KozhevnikovDmitry commented on src/Byndyusoft.DotNet.Testing.Infrastructure/ReadmeGeneration/Interfaces/ITestCaseSolutionReporter.cs
> +    Task<bool> BuildAndSave(params Assembly[] assemblies);
Метод делает ровно то, что от него требуется. Я ещё подумаю над именованием и возвращаемым значением. Пока остановится на AddReport и enum'е со статусом консистентности отчёта.